// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportIRFile() {
  return window['go']['main']['App']['ExportIRFile']();
}

export function RunAnalysis(arg1, arg2) {
  return window['go']['main']['App']['RunAnalysis'](arg1, arg2);
}

export function SelectAudioFile() {
  return window['go']['main']['App']['SelectAudioFile']();
}
