// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dsp} from '../models';

export function ExportIRFile():Promise<void>;

export function RunAnalysis(arg1:string,arg2:string):Promise<dsp.AnalysisResult>;

export function SelectAudioFile():Promise<string>;
